CREATE TYPE "ExcelJobStatus" AS ENUM ('PROCESSING','COMPLETED','FAILED');
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"name" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"refreshTokenHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "ExcelJob" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"originalName" TEXT NOT NULL,"outputPath" TEXT,"status" "ExcelJobStatus" NOT NULL DEFAULT 'PROCESSING',"errorMessage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ExcelJob_pkey" PRIMARY KEY ("id"));
ALTER TABLE "ExcelJob" ADD CONSTRAINT "ExcelJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
